-- Database Schema for POSKOKA-ES (Voluntrain)
-- Run this in the Supabase SQL Editor to initialize your database structure.

-- 1. Enable Row Level Security (RLS)
-- Each table will have policies to restrict access based on user roles.

-- 2. Create Types (Enums) for better data integrity
CREATE TYPE user_role AS ENUM ('volunteer', 'pengurus', 'korlap', 'admin');
CREATE TYPE attendance_status AS ENUM ('hadir', 'pending', 'alpha', 'sakit', 'izin');
CREATE TYPE report_severity AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE report_category AS ENUM ('kesehatan', 'keamanan', 'fasilitas', 'lainnya');
CREATE TYPE station_code AS ENUM ('BD', 'KAC', 'ALL'); -- Bandung, Kiaracondong

-- 3. Volunteers Table (Users)
-- Links to Supabase Auth.users via user_id
CREATE TABLE public.volunteers (
    id UUID REFERENCES auth.users(id) PRIMARY KEY, -- Links directly to Supabase Auth ID
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    no_anggota TEXT UNIQUE, -- e.g., VT-2024-001
    phone TEXT,
    station station_code DEFAULT 'BD',
    role user_role DEFAULT 'volunteer', -- Default role for new signups
    status TEXT DEFAULT 'pending', -- Default 'pending' usually, or 'verified' for demo
    tahun_masuk INTEGER,
    domisili TEXT,
    domisili_details JSONB, -- Full address details from wilayah.id
    preferred_station station_code,
    preferred_session TEXT,
    preferred_date DATE,
    is_flexible BOOLEAN DEFAULT false,
    total_sessions INTEGER DEFAULT 0, -- Calculated field for dashboard
    avatar_url TEXT
);
ALTER TABLE public.volunteers ENABLE ROW LEVEL SECURITY;

-- 4. Schedules Table
-- Stores daily schedules per station and session
CREATE TABLE public.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date DATE NOT NULL,
    station station_code NOT NULL,
    session TEXT NOT NULL, -- 'pagi', 'siang', 'sore'
    volunteers UUID[] DEFAULT '{}', -- Array of volunteer IDs assigned
    assignments JSONB DEFAULT '{}', -- Details of specific positions: { "user_id": "guard_post_id" }
    notes TEXT
);
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

-- 5. Attendance Table
-- Logs for check-in and check-out
CREATE TABLE public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    volunteer_id UUID REFERENCES public.volunteers(id) ON DELETE CASCADE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    station station_code NOT NULL,
    session TEXT NOT NULL,
    check_in TIME,
    check_out TIME,
    method TEXT DEFAULT 'gps', -- 'gps', 'kiosk', 'korlap'
    status attendance_status DEFAULT 'hadir',
    notes TEXT
);
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- 6. Registrations Table (Pending Volunteers)
CREATE TABLE public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id), -- Optional link if they sign up first
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    station station_code DEFAULT 'BD',
    dates DATE[], -- Array of available dates
    status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    domisili TEXT,
    tahun_masuk INTEGER
);
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- 7. Reports Table (Incident Reports)
CREATE TABLE public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    volunteer_id UUID REFERENCES public.volunteers(id) ON DELETE SET NULL,
    station station_code NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    time TIME DEFAULT CURRENT_TIME,
    category report_category DEFAULT 'lainnya',
    severity report_severity DEFAULT 'medium',
    description TEXT NOT NULL,
    status TEXT DEFAULT 'open', -- 'open', 'investigating', 'resolved'
    image_url TEXT
);
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- 8. BKO Requests Table (Bantuan Kendali Operasi)
CREATE TABLE public.bko_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    requestor_id UUID REFERENCES public.volunteers(id), -- Reporting user
    name TEXT NOT NULL, -- Name of BKO volunteer
    station station_code NOT NULL,
    dates DATE[] NOT NULL,
    session TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    linked_volunteer_id UUID REFERENCES public.volunteers(id) -- If BKO is an existing member
);
ALTER TABLE public.bko_requests ENABLE ROW LEVEL SECURITY;


-- 9. Row Level Security (RLS) Policies
-- BASIC POLICIES (Adjust as needed for strictness)

-- Volunteers: Everyone can read basic info (for roster), only admins/self can edit
CREATE POLICY "Public profiles are viewable by everyone" ON public.volunteers FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.volunteers FOR UPDATE USING (auth.uid() = id);

-- Schedules: Readable by everyone, editable by Admin/Pengurus
CREATE POLICY "Schedules are viewable by everyone" ON public.schedules FOR SELECT USING (true);
CREATE POLICY "Admins/Pengurus can insert schedules" ON public.schedules FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.volunteers WHERE id = auth.uid() AND role IN ('admin', 'pengurus'))
);
CREATE POLICY "Admins/Pengurus can update schedules" ON public.schedules FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.volunteers WHERE id = auth.uid() AND role IN ('admin', 'pengurus'))
);

-- Attendance: Readable by everyone (dashboard stats), Insertable by self (check-in) or Admin/Korlap
CREATE POLICY "Attendance viewable by everyone" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Volunteers can check-in themselves" ON public.attendance FOR INSERT WITH CHECK (auth.uid() = volunteer_id);
CREATE POLICY "Volunteers can update own check-out" ON public.attendance FOR UPDATE USING (auth.uid() = volunteer_id);
CREATE POLICY "Korlap/Admin can manage attendance" ON public.attendance FOR ALL USING (
    EXISTS (SELECT 1 FROM public.volunteers WHERE id = auth.uid() AND role IN ('admin', 'korlap'))
);

-- Registrations: Customizable logic (usually public insert, admin view)
CREATE POLICY "Anyone can register" ON public.registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins/Pengurus can view registrations" ON public.registrations FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.volunteers WHERE id = auth.uid() AND role IN ('admin', 'pengurus'))
);

-- BKO: Customizable logic (Korlap/Admin view/edit)
CREATE POLICY "Korlap/Admin manage BKO" ON public.bko_requests FOR ALL USING (
    EXISTS (SELECT 1 FROM public.volunteers WHERE id = auth.uid() AND role IN ('admin', 'korlap'))
);

-- Reports: Viewable by Admin/Korlap/Pengurus, Insertable by Volunteers
CREATE POLICY "Reports viewable by staff" ON public.reports FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.volunteers WHERE id = auth.uid() AND role IN ('admin', 'korlap', 'pengurus'))
);
CREATE POLICY "Volunteers can Create Reports" ON public.reports FOR INSERT WITH CHECK (auth.uid() = volunteer_id);

-- 10. AUTO-CREATE PROFILE TRIGGER
-- This ensures every new Auth User automatically gets a Volunteer profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.volunteers (id, email, name, role, status, no_anggota, domisili, domisili_details, station, preferred_session, preferred_date, is_flexible)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name', -- You can pass metadata during signup
    'volunteer',
    'verified', -- Default to verified to simplify testing!
    new.raw_user_meta_data->>'no_anggota',
    new.raw_user_meta_data->>'domisili',
    (new.raw_user_meta_data->>'domisili_details')::jsonb,
    (new.raw_user_meta_data->>'station')::station_code,
    new.raw_user_meta_data->>'preferred_session',
    (new.raw_user_meta_data->>'preferred_date')::date,
    (new.raw_user_meta_data->>'is_flexible')::boolean
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
